# Generated by Django 3.2.2 on 2021-09-01 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CH', 'Carbohidrates'), ('PR', 'Proteins'), ('MN', 'Minerals'), ('LP', 'Lipids'), ('RS', 'Resins'), ('PH', 'Phenolics'), ('NC', 'Natural Composites')], max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('chemical_formula', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('img_link', models.URLField()),
                ('creation_date', models.DateField(default=datetime.datetime(2021, 9, 1, 16, 9, 14, 676141, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('value', models.IntegerField()),
                ('type', models.CharField(choices=[('g', 'Grams'), ('ml', 'Milliliters')], max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.material')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_end.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='back_end.recipe')),
            ],
        ),
    ]
