# Generated by Django 3.2.2 on 2021-09-01 16:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('back_end', '0003_alter_recipe_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 16, 45, 26, 463720, tzinfo=utc)),
        ),
    ]
